### ISSUE TITLE
Add update! rule for linear IRL

### ISSUE THREAD

**Issue by JinraeKim** [fdcl-data-driven-control/DataDrivenControl.jl#7]
extended from #6.

**Comment by hnlee77** [comment]
알고리즘 중 [이 부분](https://github.com/fdcl-data-driven-control/DataDrivenControl.jl/pull/6/files#diff-cdf3cd8de1b3b31a58f929db7a5889b177f41d5f5ba00a250346e44d18ae6018R33)에 대한 논의가 필요함.

**Comment by JinraeKim** [comment]
> 알고리즘 중 [이 부분](https://github.com/fdcl-data-driven-control/DataDrivenControl.jl/pull/6/files#diff-cdf3cd8de1b3b31a58f929db7a5889b177f41d5f5ba00a250346e44d18ae6018R33)에 대한 논의가 필요함.

원래는 [ApproximateDPs.jl의 코드](https://github.com/hnlee77/ApproximateDPs.jl/blob/main/src/algorithms/irl/CTLinearValueIterationIRL.jl) 에서 따온 것으로, 이를 확인하면 좋을듯.

+) 코드를 보아하니 Eq. (99) 에서 least square 를 취한 것으로 보이며 (아래 그림), `phis` 의 인덱스를 `end-N:end-1` 로 취하는 이유는 인버스에 대응하는 데이터가 `phi(x(t))` 에 대응하기 때문으로 보임 (not `phi(x(t+T))`).
`\hat{V}_nexts` 는 (99) 의 우변에 대응함.
![image](https://user-images.githubusercontent.com/43136096/147734499-dbc426c0-a165-4f09-9e4f-6e8bd4866764.png)
